### ISSUE TITLE
When trying to just render without creating tree the error Uncaught ReferenceError: createTree is not defined

### ISSUE THREAD

**Issue by Starz26** [pgrabovets/json-view#20]
Code uses an array of json data and it works fine if I use `.render()` but when trying

`const tree = jsonview.renderJSON(data, Sizzle('#resultsDiv')[0]);`

I get the error:

Uncaught ReferenceError: createTree is not defined
    at Module.k (jsonview.js:1:7164)

and when looking as the JS there seems to be no function named `createTree()`

**Comment by pgrabovets** [comment]
Thanks dude. It has been fixed by last PR.
