### ISSUE TITLE
Question about support for big numbers

### ISSUE THREAD

**Issue by sseide** [pgrabovets/json-view#6]
Hello,
after quick check json-view dos not support display of big numbers right now - the values are changed and wrong data show (problem of javascript runtime itself and JSON.parse()). Do you plan to support big numbers or willing to accept pull request to add support?

Whats not working: `{ "pi":66110734225681139 }`
Will be changed to: `{ "pi":66110734225681140 }`

Currently we are using another library to display formatted json (jquery.json-viewer) but the development of this library seems to has stopped and my pull request to support big numbers is not answered.

Before starting to rewrite our app i'd like to ask if this is a welcome addition or not?

**Comment by pgrabovets** [comment]
Hello,
I am not planing add support of big numbers.

**Comment by sseide** [comment]
Ok - so i understand its of no use to create a PR as you will not accept it too...

Thanks for clarification.

**Comment by APayerl** [comment]
@sseide Actually json-view already seems to support BigInt... If you create an object `{ myValue: 66110734225681139n }` and end it with a 'n' (signalling it's a BigInt data type) then it will be displayed as 66110734225681139 in the resulting tree!

**Comment by sseide** [comment]
@APayerl - thanks for the remark.Fiddled around with the demo-page and it seems to work. My problem was that i get a JSON formatted string and cannot hardcode it inside the code as `123n`. Retested now and `BigInt("66110734225681139") ` works too. Thought i had tested it before and it failed...

thanks
